<a href="https://colab.research.google.com/github/GarimaSingh0109/SALES_DataAnalysis/blob/main/DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

# Get user input as a list of numbers
nums = list(map(float, input("Enter numbers separated by space: ").split()))

print("MAX:", max(nums))
print("MIN:", min(nums))
print("AVG:", sum(nums)/len(nums))
print("SUM:", sum(nums))
print("SQRT of each number:", [math.sqrt(n) for n in nums])
print("Rounded values:", [round(n) for n in nums])


Enter numbers separated by space: 2 3 6 4 33 7 87  44 12 
MAX: 87.0
MIN: 2.0
AVG: 22.0
SUM: 198.0
SQRT of each number: [1.4142135623730951, 1.7320508075688772, 2.449489742783178, 2.0, 5.744562646538029, 2.6457513110645907, 9.327379053088816, 6.6332495807108, 3.4641016151377544]
Rounded values: [2, 3, 6, 4, 33, 7, 87, 44, 12]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
# Handling missing data
df = pd.read_csv('/content/sales.csv')
print("Original Data:\n", df.head())

Original Data:
    ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0      10107.0             30.0      95.70              2.0  2871.00   
1      10121.0             34.0      81.35              5.0  2765.90   
2      10134.0             41.0      94.74              2.0  3884.34   
3      10145.0             45.0      83.26              6.0  3746.70   
4      10168.0             36.0      96.66              1.0  3479.76   

    ORDERDATE  DAYS_SINCE_LASTORDER   STATUS  PRODUCTLINE  MSRP PRODUCTCODE  \
0  24-02-2018                 828.0  Shipped  Motorcycles  95.0    S10_1678   
1  07-05-2018                 757.0  Shipped  Motorcycles  95.0    S10_1678   
2  01-07-2018                 703.0  Shipped  Motorcycles  95.0    S10_1678   
3  25-08-2018                 649.0  Shipped  Motorcycles  95.0    S10_1678   
4  28-10-2018                 586.0  Shipped  Motorcycles  95.0    S10_1678   

           CUSTOMERNAME             PHONE                   ADDRESSLINE1  \


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
# Handling missing data
df = pd.read_csv('/content/sales.csv')
print("Original Data:\n", df.head())
# Fill missing values (you can also use .dropna())
df_filled = df.fillna(df.mean(numeric_only=True))
print("After Filling Missing Data:\n", df_filled.head())

Original Data:
    ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0      10107.0             30.0      95.70              2.0  2871.00   
1      10121.0             34.0      81.35              5.0  2765.90   
2      10134.0             41.0      94.74              2.0  3884.34   
3      10145.0             45.0      83.26              6.0  3746.70   
4      10168.0             36.0      96.66              1.0  3479.76   

    ORDERDATE  DAYS_SINCE_LASTORDER   STATUS  PRODUCTLINE  MSRP PRODUCTCODE  \
0  24-02-2018                 828.0  Shipped  Motorcycles  95.0    S10_1678   
1  07-05-2018                 757.0  Shipped  Motorcycles  95.0    S10_1678   
2  01-07-2018                 703.0  Shipped  Motorcycles  95.0    S10_1678   
3  25-08-2018                 649.0  Shipped  Motorcycles  95.0    S10_1678   
4  28-10-2018                 586.0  Shipped  Motorcycles  95.0    S10_1678   

           CUSTOMERNAME             PHONE                   ADDRESSLINE1  \


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd
# Handling missing data
df = pd.read_csv('/content/sales.csv')
print("Original Data:\n", df.head())
# Fill missing values (you can also use .dropna())
df_filled = df.fillna(df.mean(numeric_only=True))
print("After Filling Missing Data:\n", df_filled.head())
# Min-Max Normalization
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(df_filled.select_dtypes(include=[np.number]))

df_normalized = pd.DataFrame(normalized_data, columns=df_filled.select_dtypes(include=[np.number]).columns)
print("Normalized Data:\n", df_normalized.head())

Original Data:
    ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0      10107.0             30.0      95.70              2.0  2871.00   
1      10121.0             34.0      81.35              5.0  2765.90   
2      10134.0             41.0      94.74              2.0  3884.34   
3      10145.0             45.0      83.26              6.0  3746.70   
4      10168.0             36.0      96.66              1.0  3479.76   

    ORDERDATE  DAYS_SINCE_LASTORDER   STATUS  PRODUCTLINE  MSRP PRODUCTCODE  \
0  24-02-2018                 828.0  Shipped  Motorcycles  95.0    S10_1678   
1  07-05-2018                 757.0  Shipped  Motorcycles  95.0    S10_1678   
2  01-07-2018                 703.0  Shipped  Motorcycles  95.0    S10_1678   
3  25-08-2018                 649.0  Shipped  Motorcycles  95.0    S10_1678   
4  28-10-2018                 586.0  Shipped  Motorcycles  95.0    S10_1678   

           CUSTOMERNAME             PHONE                   ADDRESSLINE1  \


In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('/content/sales.csv')

# Select only numeric columns
numeric_df = df.select_dtypes(include=[np.number])

# Drop rows with missing values (optional – or you can fill with mean/median)
numeric_df = numeric_df.dropna()

# Perform statistical operations column-wise
for column in numeric_df.columns:
    col_data = numeric_df[column]
    print(f"\nColumn: {column}")
    print("Mean:", np.mean(col_data))
    print("Median:", np.median(col_data))
    print("Mode:", col_data.mode().iloc[0])  # Taking the first mode if multiple
    print("Standard Deviation:", np.std(col_data, ddof=1))  # Sample std deviation



Column: ORDERNUMBER
Mean: 10259.761558063341
Median: 10264.0
Mode: 10106.0
Standard Deviation: 91.87752071650719

Column: QUANTITYORDERED
Mean: 35.10302147797597
Median: 35.0
Mode: 34.0
Standard Deviation: 9.76213542350501

Column: PRICEEACH
Mean: 101.09895158354568
Median: 95.55
Mode: 59.87
Standard Deviation: 42.04254924789503

Column: ORDERLINENUMBER
Mean: 6.4910811794685115
Median: 6.0
Mode: 1.0
Standard Deviation: 4.230543549164283

Column: SALES
Mean: 3553.0475828176195
Median: 3184.8
Mode: 1030.44
Standard Deviation: 1838.9539005448687

Column: DAYS_SINCE_LASTORDER
Mean: 1757.085911903895
Median: 1761.0
Mode: 2207.0
Standard Deviation: 819.2805762875169

Column: MSRP
Mean: 100.69166363305425
Median: 99.0
Mode: 118.0
Standard Deviation: 40.11480174959149


In [ ]:
import pandas as pd
import numpy as np

# Load numeric data from the uploaded dataset
df = pd.read_csv('/content/sales.csv')
matrix = df.select_dtypes(include=[np.number]).dropna().values  # Convert to NumPy array

# Ensure matrix is 2D and of compatible shape
if matrix.shape[0] >= 3 and matrix.shape[1] >= 3:
    # Use only first 3x3 part of matrix to ensure square matrix for inverse
    matrix1 = matrix[:3, :3]
    matrix2 = matrix[3:6, :3]  # next 3 rows for same shape
else:
    raise ValueError("Need at least 6 rows and 3 columns of numeric data.")

# Display the matrices
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Operations
print("\nAddition:\n", matrix1 + matrix2)
print("\nSubtraction:\n", matrix1 - matrix2)
print("\nMultiplication (Matrix Dot Product):\n", np.dot(matrix1, matrix2.T))
print("\nTranspose of Matrix 1:\n", matrix1.T)

# Inverse (only possible for square & non-singular matrix)
try:
    inverse = np.linalg.inv(matrix1)
    print("\nInverse of Matrix 1:\n", inverse)
except np.linalg.LinAlgError:
    print("\nMatrix 1 is singular and cannot be inverted.")

# Element-wise Division (avoiding division by zero)
with np.errstate(divide='ignore', invalid='ignore'):
    division = np.true_divide(matrix1, matrix2)
    division[np.isnan(division)] = 0  # Replace nan with 0
    print("\nElement-wise Division:\n", division)


Matrix 1:
 [[10107.      30.      95.7 ]
 [10121.      34.      81.35]
 [10134.      41.      94.74]]
Matrix 2:
 [[10145.      45.      83.26]
 [10168.      36.      96.66]
 [10180.      29.      86.13]]

Addition:
 [[20252.      75.     178.96]
 [20289.      70.     178.01]
 [20314.      70.     180.87]]

Subtraction:
 [[-38.   -15.    12.44]
 [-47.    -2.   -15.31]
 [-46.    12.     8.61]]

Multiplication (Matrix Dot Product):
 [[1.02544833e+08 1.02778306e+08 1.02898373e+08]
 [1.02685848e+08 1.02919415e+08 1.03039773e+08]
 [1.02819163e+08 1.03053146e+08 1.03173469e+08]]

Transpose of Matrix 1:
 [[10107.   10121.   10134.  ]
 [   30.      34.      41.  ]
 [   95.7     81.35    94.74]]

Inverse of Matrix 1:
 [[-7.36823305e-05  6.97849553e-04 -5.24790607e-04]
 [-8.67634704e-02 -7.92807422e-03  9.44502106e-02]
 [ 4.54295865e-02 -7.12154985e-02  2.58155940e-02]]

Element-wise Division:
 [[0.99625431 0.66666667 1.14941148]
 [0.99537766 0.94444444 0.84160977]
 [0.99548134 1.4137931  1.09996

In [ ]:
import pandas as pd

# Load CSV file
df = pd.read_csv('/content/sales.csv')
print("CSV File Loaded Successfully:\n")
print(df.head())


CSV File Loaded Successfully:

   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0      10107.0             30.0      95.70              2.0  2871.00   
1      10121.0             34.0      81.35              5.0  2765.90   
2      10134.0             41.0      94.74              2.0  3884.34   
3      10145.0             45.0      83.26              6.0  3746.70   
4      10168.0             36.0      96.66              1.0  3479.76   

    ORDERDATE  DAYS_SINCE_LASTORDER   STATUS  PRODUCTLINE  MSRP PRODUCTCODE  \
0  24-02-2018                 828.0  Shipped  Motorcycles  95.0    S10_1678   
1  07-05-2018                 757.0  Shipped  Motorcycles  95.0    S10_1678   
2  01-07-2018                 703.0  Shipped  Motorcycles  95.0    S10_1678   
3  25-08-2018                 649.0  Shipped  Motorcycles  95.0    S10_1678   
4  28-10-2018                 586.0  Shipped  Motorcycles  95.0    S10_1678   

           CUSTOMERNAME             PHONE                   A

Exp - 6

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

# Load the dataset
df = pd.read_csv('/content/sales.csv')

# Step 1: Drop rows with missing values
df_clean = df.dropna()

# Step 2: Encode categorical variables
df_encoded = df_clean.copy()
label_encoders = {}
categorical_cols = df_encoded.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    label_encoders[col] = le

# Step 3: Drop unnecessary columns
drop_cols = ['ORDERNUMBER', 'ORDERDATE', 'PRODUCTCODE', 'CUSTOMERNAME',
             'PHONE', 'ADDRESSLINE1', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME']
df_features = df_encoded.drop(columns=drop_cols)

# Step 4: Define features (X) and target (y)
X = df_features.drop(columns=['DEALSIZE'])
y = df_features['DEALSIZE']

# Step 5: Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 6: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 7: Train and evaluate SVM without PCA
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy_no_pca = accuracy_score(y_test, y_pred)

# Step 8: Apply PCA (reduce to 2 components)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
X_train_pca, X_test_pca, _, _ = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Step 9: Train and evaluate SVM with PCA
svm_pca = SVC()
svm_pca.fit(X_train_pca, y_train)
y_pred_pca = svm_pca.predict(X_test_pca)
accuracy_pca = accuracy_score(y_test, y_pred_pca)

# Step 10: Print accuracies
print("Accuracy without PCA:", accuracy_no_pca)
print("Accuracy with PCA (2 components):", accuracy_pca)


Accuracy without PCA: 0.9690909090909091
Accuracy with PCA (2 components): 0.8581818181818182


In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score

# Load the dataset
df = pd.read_csv('/content/sales.csv')

# Drop rows with missing values
df_clean = df.dropna()

# Encode categorical variables
df_encoded = df_clean.copy()
label_encoders = {}
categorical_cols = df_encoded.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])
    label_encoders[col] = le

# Drop non-informative or identifier columns
drop_cols = ['ORDERNUMBER', 'ORDERDATE', 'PRODUCTCODE', 'CUSTOMERNAME',
             'PHONE', 'ADDRESSLINE1', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME']
df_features = df_encoded.drop(columns=drop_cols)

# Define features and target
X = df_features.drop(columns=['DEALSIZE'])
y = df_features['DEALSIZE']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# SVM without PCA
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy_no_pca = accuracy_score(y_test, y_pred)

# Apply PCA to reduce dimensions to 2
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
X_train_pca, X_test_pca, _, _ = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# SVM with PCA
svm_pca = SVC()
svm_pca.fit(X_train_pca, y_train)
y_pred_pca = svm_pca.predict(X_test_pca)
accuracy_pca = accuracy_score(y_test, y_pred_pca)

# Print comparison
print("Accuracy without PCA:", round(accuracy_no_pca * 100, 2), "%")
print("Accuracy with PCA (2 components):", round(accuracy_pca * 100, 2), "%")


Accuracy without PCA: 96.91 %
Accuracy with PCA (2 components): 85.82 %
